### ISSUE TITLE
Proper branches, releases and symphonyextensions.com integration

### ISSUE THREAD

**Issue by twiro** [symphonists/output_field#1]
Hey Nils,

just noticed that this nice little gem is not completely abandoned and you recently added PHP7-support – great to see & thanks for that!

As I use this extension quite often I started [a little overhaul](https://github.com/twiro/output_field/tree/integration) with [some improvements](https://github.com/twiro/output_field/blob/integration/extension.meta.xml#L18) a while back which I'd like to publish as a proper release now. As this would include…

1. Setting up an integration branch in this repo
2. Build proper releases for version 2.0.0 and the upcoming 2.1.0
3. Fixing the extension at [symphonyextensions.com](http://symphonyextensions.com/extensions/output_field/) and resubmit it under the [Symphonists](http://symphonyextensions.com/developers/symphonists/)-account

… it would be great if you (or @nitriques ?) could give me write access to this repo as I would gladly take care about these things!

**Comment by nilshoerrmann** [comment]
Thanks for taking care of this extension!

Access to the Symphonist repos is usually handled on a organisation level so I think it's best for @nitriques to take a look into this. I don't know how these things are currently set up internally.

**Comment by twiro** [comment]
Thanks Nils!

@nitriques – Would you mind adding me to the Symphonists organisation? There are [some](https://github.com/symphonists/reflectionfield) [repos](https://github.com/symphonists/association_field) I use on a regularly basis and would like to help with as good as I can (don't worry, I would still ask whend doing critical coding stuff ;)

**Comment by nitriques** [comment]
@twiro Done, you should now have access to 106 repos !

**Comment by twiro** [comment]
Thank you very much Nicolas :)

Now that I've got a little more responsibility on github it would be nice if you could help me with one question that I'm still struggling with when working with extension-repos:

Whenever I set up an [integration-branch](https://github.com/symphonists/output_field/tree/integration) and [submit all my changes](https://github.com/symphonists/output_field/commits/integration) against I come to the point where I want to _merge_ my changes from `integration` into the `master`-branch.

As I'm still a total command-line-noob (and probably always will be) I mostly use the Github desktop app to work with git and there I see two possibilities to handle this:

1. Create a PR from `integration` to `master`
2. Merge changes from `integration` into `master` by choosing "compare with integration" and then "update from integration"

In both cases I end up with an `integration`-branch that is "_[1 commit behind master](https://github.com/twiro/entry_shortlink/tree/integration)_", because the `master`-branch now either has the accepted PR (1.) or the "[merge branch 'integration'](https://github.com/twiro/entry_shortlink/commits/master)"(2.)  as additional commit.

But I see a lot of extensions that show me "_This branch is even with master._" when I look at their `integration`-branch and I'd really like to know how to achieve this – So to summarise my question:

How do I "_sync_" a `master`-branch with an  `integration`-branch and end up with two "_even_" branches after that (Avoiding that master is one commit ahead after the "_sync_")?

**Comment by twiro** [comment]
> _How do I "sync" a master-branch with an integration-branch and end up with two "even" branches after that (Avoiding that master is one commit ahead after the "sync")?_

Figured it out using the command line… select the master-branch and use `git merge integration` – now that was easy :)

So here is version [2.1.0](https://github.com/symphonists/output_field/releases/tag/2.1.0)!

**Comment by nitriques** [comment]
I would recommend to first try to `git merge --ff-only integration` (when checkout in master). This should always work, if the repo is well maintained. Without it, git may do a recursive merge, which will create awfull merge commits. If it fails, then you know master hash some commit integration does not, which should not happen, for the sake of everybody ;)
